import '@/styles/globalStyles.css';
import '@/styles/theme.css';

import classNames from 'classnames';
import type { Metadata } from 'next';

import { Providers } from '@/contexts';
import { container } from '@/styles/layout.css';

import { pretendard } from './font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={classNames(pretendard.className)}>
        <Providers>
          <main className={classNames(container)}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
