import '@/styles/globalStyles.css';
import '@/styles/theme.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from '@/contexts';
import { container } from '@/styles/layout.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={`${inter.className}`}>
        <Providers>
          <main className={`${container}`}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
